# Generated by Django 5.0.6 on 2024-06-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_persona_donador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
